### ISSUE TITLE
Issues with running the demo file

### ISSUE THREAD

**Issue by shayanalipour** [JoshuaChou2018/SkinGPT-4#1]
Hi, thanks for making your work public.  
I had several issues running the demo file. The problem is that the code is based on falcon-40b (and other non-public trained weights). The public trained weights for vicuna-7b model has different attributes. I had to change different parts of the code base to be able to run the demo file.  For example, the vicuna model doesn't have the attribute transformer. So in conversations.py we need to change self.model.llm_model.transformer.word_embeddings(seg_t) to self.model.llm_model.model.embed_tokens(seg_t). 
I had to make changes to demo.py, skingpt4/models/skin_gpt4.py, eval_configs/skingpt4_eval_vicuna.yaml (set model_type: pretrain_vicuna), etc.

I would suggest making a simpler version that runs with your public skingpt_v1 weights for the demo case. Thanks again.

**Comment by JoshuaChou2018** [comment]
Hi, thank you for your suggestion! As you have noticed, our public model skingpt_v1 is an old version based on vicuna-7b, while the latest versions are currently based on falcon-40b and llama2 (not publicly available). If you want to test the old version skingpt_v1, you can directly insert the model to https://github.com/Vision-CAIR/MiniGPT-4

**Comment by shayanalipour** [comment]
Thank you. I can run the minigpt-4 demo successfully, but when i replace their weights `prerained_minigpt4_7b.pth` with yours `skingpt.pth.` I get the size mismatch error:
`RuntimeError: Error(s) in loading state_dict for MiniGPT4:
	size mismatch for llama_proj.weight: copying a param with shape torch.Size([5120, 768]) from checkpoint, the shape in current model is torch.Size([4096, 768]).
	size mismatch for llama_proj.bias: copying a param with shape torch.Size([5120]) from checkpoint, the shape in current model is torch.Size([4096]).`

**Comment by Rishi-Kumar7** [comment]
> Hi, thanks for making your work public. I had several issues running the demo file. The problem is that the code is based on falcon-40b (and other non-public trained weights). The public trained weights for vicuna-7b model has different attributes. I had to change different parts of the code base to be able to run the demo file. For example, the vicuna model doesn't have the attribute transformer. So in conversations.py we need to change self.model.llm_model.transformer.word_embeddings(seg_t) to self.model.llm_model.model.embed_tokens(seg_t). I had to make changes to demo.py, skingpt4/models/skin_gpt4.py, eval_configs/skingpt4_eval_vicuna.yaml (set model_type: pretrain_vicuna), etc.
> 
> I would suggest making a simpler version that runs with your public skingpt_v1 weights for the demo case. Thanks again.



> Thank you. I can run the minigpt-4 demo successfully, but when i replace their weights `prerained_minigpt4_7b.pth` with yours `skingpt.pth.` I get the size mismatch error: `RuntimeError: Error(s) in loading state_dict for MiniGPT4: size mismatch for llama_proj.weight: copying a param with shape torch.Size([5120, 768]) from checkpoint, the shape in current model is torch.Size([4096, 768]). size mismatch for llama_proj.bias: copying a param with shape torch.Size([5120]) from checkpoint, the shape in current model is torch.Size([4096]).`



> Hi, thanks for making your work public. I had several issues running the demo file. The problem is that the code is based on falcon-40b (and other non-public trained weights). The public trained weights for vicuna-7b model has different attributes. I had to change different parts of the code base to be able to run the demo file. For example, the vicuna model doesn't have the attribute transformer. So in conversations.py we need to change self.model.llm_model.transformer.word_embeddings(seg_t) to self.model.llm_model.model.embed_tokens(seg_t). I had to make changes to demo.py, skingpt4/models/skin_gpt4.py, eval_configs/skingpt4_eval_vicuna.yaml (set model_type: pretrain_vicuna), etc.
> 
> I would suggest making a simpler version that runs with your public skingpt_v1 weights for the demo case. Thanks again.

Hi @shayanalipour, greetings, shall I ask if you could run it ? and if yes would you be able to show the changes you have made to make it work? using the original repo and also if with the work around solution repo: https://github.com/Vision-CAIR/MiniGPT-4.   Kindly support

**Comment by Rishi-Kumar7** [comment]
> Hi, thank you for your suggestion! As you have noticed, our public model skingpt_v1 is an old version based on vicuna-7b, while the latest versions are currently based on falcon-40b and llama2 (not publicly available). If you want to test the old version skingpt_v1, you can directly insert the model to https://github.com/Vision-CAIR/MiniGPT-4

I am getting the following error after inserting the skingpt_v1:

`(minigpt4) [ec2-user@ip-172-31-43-93 MiniGPT-4]$ python demo.py --cfg-path eval_configs/minigpt4_eval.yaml  --gpu-id 0

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
Initializing Chat
/opt/conda/envs/minigpt4/lib/python3.9/site-packages/transformers/tokenization_utils_base.py:1727: FutureWarning: Calling LlamaTokenizer.from_pretrained() with the path to a single file or url is deprecated and won't be possible anymore in v5. Use a model identifier or the path to a directory instead.
  warnings.warn(
Traceback (most recent call last):
  File "/home/ec2-user/SkinGPT-4/MiniGPT-4/demo.py", line 65, in <module>
    model = model_cls.from_config(model_config).to('cuda:{}'.format(args.gpu_id))
  File "/home/ec2-user/SkinGPT-4/MiniGPT-4/minigpt4/models/minigpt4.py", line 169, in from_config
    model = cls(
  File "/home/ec2-user/SkinGPT-4/MiniGPT-4/minigpt4/models/minigpt4.py", line 45, in __init__
    super().__init__(
  File "/home/ec2-user/SkinGPT-4/MiniGPT-4/minigpt4/models/minigpt_base.py", line 41, in __init__
    self.llama_model, self.llama_tokenizer = self.init_llm(
  File "/home/ec2-user/SkinGPT-4/MiniGPT-4/minigpt4/models/base_model.py", line 174, in init_llm
    llama_tokenizer = LlamaTokenizer.from_pretrained(llama_model_path, use_fast=False)
  File "/opt/conda/envs/minigpt4/lib/python3.9/site-packages/transformers/tokenization_utils_base.py", line 1825, in from_pretrained
    return cls._from_pretrained(
  File "/opt/conda/envs/minigpt4/lib/python3.9/site-packages/transformers/tokenization_utils_base.py", line 1988, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
  File "/opt/conda/envs/minigpt4/lib/python3.9/site-packages/transformers/models/llama/tokenization_llama.py", line 96, in __init__
    self.sp_model.Load(vocab_file)
  File "/opt/conda/envs/minigpt4/lib/python3.9/site-packages/sentencepiece/__init__.py", line 905, in Load
    return self.LoadFromFile(model_file)
  File "/opt/conda/envs/minigpt4/lib/python3.9/site-packages/sentencepiece/__init__.py", line 310, in LoadFromFile
    return _sentencepiece.SentencePieceProcessor_LoadFromFile(self, arg)
RuntimeError: Internal: src/sentencepiece_processor.cc(1101) [model_proto->ParseFromArray(serialized.data(), serialized.size())] `





**Is it the same error in a different form referenced at this comment? : [comment link](https://github.com/JoshuaChou2018/SkinGPT-4/issues/1#issuecomment-1764503416)**

**Comment by JoshuaChou2018** [comment]
> Thank you. I can run the minigpt-4 demo successfully, but when i replace their weights `prerained_minigpt4_7b.pth` with yours `skingpt.pth.` I get the size mismatch error:
> `RuntimeError: Error(s) in loading state_dict for MiniGPT4: size mismatch for llama_proj.weight: copying a param with shape torch.Size([5120, 768]) from checkpoint, the shape in current model is torch.Size([4096, 768]). size mismatch for llama_proj.bias: copying a param with shape torch.Size([5120]) from checkpoint, the shape in current model is torch.Size([4096]).`

Hi, it looks minigpt-4 has also been updated, our trained weight should work well for an older version of minigpt-4, no worries, we will release a llama2 version soon, which is more powerful than the vicuna-based version.
